# Logistic Regression & Cross Validation

In this exercise, you will use logistic regression to classify breast cancer as either malignant or benign. First run the code below to print and read the description of the data set. 

In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

DataCancer=load_breast_cancer()
#print(DataCancer.keys())
#print(DataCancer.DESCR)





### A) Use logistic regression, with ridge regularization and tuning parameter set to 1. Find the accuracy of the model. Scale the features  to have zero mean and unit variance. 
- Use random_state = 0 in the train_test_split.

In [3]:
X_features=DataCancer.data
Y_targetClass=DataCancer.target
X_train, X_test, Y_train, Y_test = train_test_split(X_features,Y_targetClass,random_state=0)
scaler=preprocessing.StandardScaler().fit(X_train)
X_train_transformed=scaler.transform(X_train) #apply scaling on training set
X_test_transformed=scaler.transform(X_test) #apply scaling on test set
LogRegModel= LogisticRegression(C=1).fit(X_train_transformed, Y_train)
print("the accuracy of the model is",LogRegModel.score(X_test_transformed,Y_test))


the accuracy of the model is 0.958041958041958


### B) For the same problem, we also use logistic regression but want to select the best tuning parameter of Ridge regularization in logistic regression. We try the following set of values for the tuning parameter: [0.01, 0.1, 1, 10, 100], and use the five fold cross validation. Find the best tuning parameter in this set, and the test accuracy of the model when the best tuning parameter is selected. 
- Feature scaled as in part A

In [4]:
from sklearn.model_selection import cross_val_score


kfolds=5   # set number of folds=5
bestscore=0 # set best score =0
X_trainval, X_test, Y_trainval, Y_test= train_test_split(DataCancer.data, DataCancer.target, random_state=0)
X_trainval_transformed=scaler.transform(X_trainval) #apply scaling on training set
X_test_transformed=scaler.transform(X_test) #apply scaling on test set

for x in [0.01, 0.1, 1, 10, 100]:
    LogRegModel= LogisticRegression(C=x)   # fitting using training set
    scores = cross_val_score(LogRegModel, X_trainval_transformed, Y_trainval, cv=kfolds)   #evalutaion using valition set
    score=np.mean(scores)
    print(scores)
    
    if score>bestscore:
        
        bestscore = score
        bestparameter = x
        
BestLogRegModel=LogisticRegression(C=bestparameter).fit(X_trainval_transformed, Y_trainval)
print("the accuracy of best selected  model is",BestLogRegModel.score(X_test_transformed,Y_test))
print("the best parameter is ",bestparameter)

[0.95348837 0.97674419 0.95294118 0.98823529 0.98809524]
[0.98837209 0.98837209 0.95294118 1.         0.98809524]
[0.98837209 0.98837209 0.95294118 1.         0.97619048]
[0.98837209 0.96511628 0.94117647 1.         0.98809524]
[0.96511628 0.96511628 0.92941176 0.98823529 0.98809524]
the accuracy of best selected  model is 0.965034965034965
the best parameter is  0.1
